<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Folder Include="Migrations\" />
    <Folder Include="Queries\" />
    <Folder Include="Repositories\Abstract\" />
    <Folder Include="Repositories\Model\" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="9.0.8" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\ToDoAppServer.Application\ToDoAppServer.Application.csproj" />
    <ProjectReference Include="..\ToDoAppServer.Domain\ToDoAppServer.Domain.csproj" />
  </ItemGroup>

</Project>
